sudo: required

language: python

services:
  - docker

before_install:
  - CHANGED_FILES=($(git diff --name-only $TRAVIS_COMMIT_RANGE))
  - echo $CHANGED_FILES
  - >
    for file in $CHANGED_FILES; do
      if [[ $file =~ "Dockerfile" ]]; then
        dockerfile=$file
        image=${dockerfile#Dockerfile.}
        travis_wait 40 docker build -t "$DOCKER_USERNAME"/$image -f $dockerfile .
        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        travis_wait docker push "$DOCKER_USERNAME"/$image
      fi
    done

script:
  - python -c "import sys; print(sys.version)"
