sudo: required

language: python

services:
  - docker

before_install:
  - travis_wait 40 docker build -t "$DOCKER_USERNAME"/ubuntu-16.04_mkl2017.4.239-pgi17.4 -f Dockerfile.ubuntu-16.04_mkl2017.4.239-pgi17.4 .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - travis_wait docker push "$DOCKER_USERNAME"/ubuntu-16.04_mkl2017.4.239-pgi17.4

script:
  - python -c "import sys; print(sys.version)"
